name: Install dotfiles
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opend
      - synchronize

jobs:
  aqua:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out Repository code
        uses: actions/checkout@v4
      - name: aqua-installer
        uses: aquaproj/aqua-installer@v3.1.1
        with:
          aqua_version: v2.45.0
      - name: aqua install
        run: aqua i -l -a

  install-dotfiles:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out Repository code
        uses: actions/checkout@v4
      - name: Run install.sh
        run: ./install.sh

  status-check:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs:
      - aqua
      - install-dotfiles
    if: ${{ failure() || cancelled() }}
    steps:
      - run: exit 1
