name: Install dotfiles
on: [push]
jobs:
  Install-Dotfiles:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository code 
        uses: actions/checkout@v4
      - name: Run install.sh
        run: ./install.sh
