name: Install dotfiles
on:
  push:
    branches:
      - main

jobs:
  aqua:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: aqua-installer
        uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
        with:
          aqua_version: v2.50.1
      - name: aqua install
        run: aqua i -l -a

  install-dotfiles:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Run install.sh
        run: ./install.sh

  status-check:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs:
      - aqua
      - install-dotfiles
    if: ${{ failure() || cancelled() }}
    steps:
      - run: exit 1
